/* ============================================================================
 * 📦 2 Contentful content type interfaces generated by contentful-typegen 🤖
 * 🛑 DO NOT EDIT THIS FILE — it is auto-generated and overwritten on each build.
 * ========================================================================== */

/** System metadata common to all Contentful entities. */
export interface Sys {
  id: string;
  type: string;
  createdAt: string;
  updatedAt: string;
  locale?: string;
  contentType?: { sys: { id: string; linkType: "ContentType"; type: "Link" } };
}

/** File metadata for an Asset (size, image dimensions). */
export interface AssetFileDetails {
  size: number;
  image?: { width: number; height: number };
}

/** File object for an Asset (URL, type, etc.). */
export interface AssetFile {
  url: string;
  details: AssetFileDetails;
  fileName: string;
  contentType: string;
}

/** Asset fields (title, description, file). */
export interface AssetFields {
  title?: string;
  description?: string;
  file?: AssetFile;
}

/** A minimal representation of a Contentful Asset. */
export interface Asset {
  sys: Sys;
  fields: AssetFields;
  metadata?: unknown;
}

/** A minimal representation of a Contentful Entry. */
export interface Entry<TFields = any> {
  sys: Sys;
  fields: TFields;
  metadata?: unknown;
}

/** Minimal Rich Text Document root node. */
export interface Document {
  nodeType: "document";
  data: Record<string, unknown>;
  content: any[];
}

/** An article model with unions and links */
export interface IArticleFields {
  title: string;
  status?: "draft" | "published";
  heroImage?: Asset;
  author?: Entry<IPersonFields>;
  related?: ReadonlyArray<Entry<IArticleFields>>;
}
export type IArticle = Entry<IArticleFields>;

/** Author */
export interface IPersonFields {
  name: string;
  role?: "Staff" | "Contributor" | "Guest";
}
export type IPerson = Entry<IPersonFields>;
